const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#draw'),ctx=canvas.getContext('2d'); let drawing=false,color='#1b1b17',paths=[],path=null,raceTimer,boosts=0,myHorseData=null;
function size(){const r=canvas.getBoundingClientRect(); canvas.width=Math.max(700,r.width*devicePixelRatio);canvas.height=Math.max(350,r.height*devicePixelRatio);redrawCanvas()}
function redrawCanvas(){ctx.fillStyle='#fafaf5';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.lineCap='round';ctx.lineJoin='round'; for(const p of paths){ctx.strokeStyle=p.color;ctx.lineWidth=5*devicePixelRatio;ctx.beginPath();p.pts.forEach((q,i)=>i?ctx.lineTo(q.x*canvas.width,q.y*canvas.height):ctx.moveTo(q.x*canvas.width,q.y*canvas.height));ctx.stroke()}}
function point(e){let r=canvas.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:(t.clientX-r.left)/r.width,y:(t.clientY-r.top)/r.height}}
canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);path={color,pts:[point(e)]};paths.push(path)}; canvas.onpointermove=e=>{if(!drawing)return;path.pts.push(point(e));redrawCanvas()}; canvas.onpointerup=()=>drawing=false;
$$('.color').forEach(b=>{b.style.setProperty('--c',b.dataset.c);b.onclick=()=>{$$('.color').forEach(x=>x.classList.remove('on'));b.classList.add('on');color=b.dataset.c}});$('#undo').onclick=()=>{paths.pop();redrawCanvas()};$('#clear').onclick=()=>{paths=[];redrawCanvas()};window.addEventListener('resize',size);size();
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function analyze(){let pts=paths.flatMap(p=>p.pts);if(pts.length<3)pts=[{x:.15,y:.55},{x:.75,y:.55},{x:.83,y:.45},{x:.88,y:.52},{x:.75,y:.6},{x:.3,y:.6}];let xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),span=Math.max(...xs)-Math.min(...xs),height=Math.max(...ys)-Math.min(...ys),ink=pts.length;let legs=0;paths.forEach(p=>{let a=p.pts[0],b=p.pts.at(-1);if(a&&b&&Math.abs(a.x-b.x)<.12&&b.y-a.y>.12)legs++});return{speed:Math.round(45+span*34+Math.min(legs,4)*4),stability:Math.round(82-Math.abs(height-.38)*80+Math.min(legs,4)*3),spirit:Math.min(99,Math.round(42+Math.log(ink+1)*9)),span,height,legs,ink}}
function dataUrl(){let out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;let c=out.getContext('2d');c.drawImage(canvas,0,0);return out.toDataURL()}
function aiSvg(kind,col){let forms=[`<path d="M8 48 L35 27 L63 38 L98 28 L128 40 L142 29 L153 33 L145 46 L127 48 M40 44 L30 70 L20 75 M65 45 L62 70 L51 74 M105 44 L112 70 L100 74 M128 44 L140 67 L153 70"/>`,`<path d="M5 52 L30 38 L50 45 L75 25 L117 32 L130 20 L148 25 L143 40 L126 44 M31 45 L23 72 L10 73 M59 44 L55 70 L45 75 M99 40 L107 69 L97 75 M123 42 L136 65 L151 67"/>`,`<path d="M6 49 Q36 12 65 43 Q89 60 112 33 L130 28 L147 37 L137 48 L120 47 M33 44 L25 71 L12 75 M58 47 L53 72 L44 75 M98 43 L106 70 L95 76 M121 45 L136 68 L150 70"/>`];return `<svg viewBox="0 0 160 85"><g fill="none" stroke="${col}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">${forms[kind]}</g></svg>`}
function startRace(){myHorseData=analyze();let name=$('#horseName').value.trim()||'Barely a horse';$('#raceTitle').textContent=name;show('#race');let laneData=[{name,me:true,score:myHorseData.speed*.5+myHorseData.stability*.25+myHorseData.spirit*.25,col:'#171713'}, {name:'LONG STORY',score:72+Math.random()*8,col:'#d22d88'}, {name:'UNSTABLE',score:68+Math.random()*15,col:'#3c68db'}, {name:'HORSE.EXE',score:70+Math.random()*12,col:'#ec6b45'}]; laneData.sort(()=>Math.random()-.5);let lanes=$('#lanes');lanes.innerHTML='';laneData.forEach((h,i)=>{let d=document.createElement('div');d.className='lane';d.style.top=i*25+'%';let runner=document.createElement('div');runner.className='runner'; if(h.me){let im=new Image();im.src=dataUrl();let cv=document.createElement('canvas');cv.width=300;cv.height=140;let cx=cv.getContext('2d');im.onload=()=>{cx.drawImage(im,0,0,300,140)};runner.append(cv)} else runner.innerHTML=aiSvg(i%3,h.col);d.append(runner);let lab=document.createElement('div');lab.className='label';lab.textContent=h.me?'YOUR HORSE':h.name;d.append(lab);lanes.append(d);h.el=d;h.pos=0;h.v=0});let count=3;$('#countdown').textContent=count;boosts=0;$('#meters').textContent='0';$('#meterBar').style.width='0';let c=setInterval(()=>{count--;$('#countdown').textContent=count||'GO!';if(count<0){clearInterval(c);$('#countdown').textContent='';run(laneData)}},650)}
function run(horses){let last=performance.now(),done=false;function frame(now){if(done)return;let dt=Math.min(.04,(now-last)/1000);last=now;horses.forEach((h,i)=>{let target=h.score*.32+(Math.sin(now/350+i)*1.8)+(h.me?boosts*.3:0);h.v+=(target-h.v)*dt*2;h.pos+=h.v*dt;h.el.style.transform=`translateX(${Math.min(h.pos,100)*.83}vw) translateY(${Math.sin(now/80+i)*3}px)`});let me=horses.find(h=>h.me);$('#meters').textContent=Math.min(100,Math.floor(me.pos));$('#meterBar').style.width=Math.min(100,me.pos)+'%';let fin=horses.filter(h=>h.pos>=100).sort((a,b)=>b.pos-a.pos);if(fin.length){done=true;clearTimeout(raceTimer);setTimeout(()=>finish(horses),500)}else requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function boost(){boosts=Math.min(14,boosts+1);$('#boost').style.boxShadow=`0 0 0 ${Math.min(12,boosts)}px rgba(213,255,57,.12)`}$('#boost').onclick=boost;addEventListener('keydown',e=>{if(e.code==='Space'&&$('#race').classList.contains('active')){e.preventDefault();boost()}});
function finish(h){let sorted=[...h].sort((a,b)=>b.pos-a.pos),place=sorted.findIndex(x=>x.me)+1,ord=['1ST.','2ND.','3RD.','4TH.'];$('#place').textContent=ord[place-1];$('#verdict').textContent=['Somehow, a champion.','A noble almost.','Technically finished.','A horse in spirit.'][place-1];$('#stats').innerHTML=[['SPEED',myHorseData.speed],['BALANCE',Math.max(10,myHorseData.stability)],['SPIRIT',myHorseData.spirit]].map(x=>`<div class="stat">${x[0]}<b>${x[1]}</b></div>`).join('');let cv=document.createElement('canvas');cv.width=canvas.width;cv.height=canvas.height;cv.getContext('2d').drawImage(canvas,0,0);$('#resultHorse').innerHTML='';$('#resultHorse').append(cv);show('#result')}
$('#raceBtn').onclick=startRace;$('#back').onclick=()=>show('#intro');$('#redraw').onclick=()=>{paths=[];redrawCanvas();show('#intro')};$('#again').onclick=startRace;let audio=null;$('#soundBtn').onclick=()=>{if(!audio){audio=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=72;g.gain.value=.02;o.connect(g).connect(audio.destination);o.start();$('#soundBtn').textContent='SOUND ON'}else{audio.close();audio=null;$('#soundBtn').textContent='SOUND OFF'}};
